language: cpp
root: true
compiler:
  - gcc
os:
  - linux
before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update
  - sudo apt-get -y install swig r-base
script:
  - make
notifications:
  email:
    on_success: change
    on_failure: change
